// use failure::Fail;
/*
#[derive(Fail, Debug)]
pub enum VyperError {
    #[fail(display = "{}", _0)]
    Io(#[fail(cause)] std::io::Error),
}

impl From<std::io::Error> for VyperError {
    fn from(err: std::io::Error) -> VyperError {
        VyperError::Io(err)
    }
}
*/
